-- Starter keyword pre-filter for search queries. GENERATED by scripts/build-keyword-seed.mjs.
-- 49 rules on the 2..6 ladder (6 explicit, 5 immodest/shtus, 2 clean instant-allow). The
-- pre-filter takes the STRICTEST match, so allow-terms are overridden by any block-term in the same
-- query. Conservative on purpose: the model is the backstop and judges every language, so extend the
-- Hebrew/Yiddish block lists with a native reviewer. Re-runnable-ish: clears prior seeded rows first.

DELETE FROM keyword_rules WHERE note IN ('explicit', 'immodest', 'clean');

INSERT INTO keyword_rules (scope, lang, pattern, rating, note)
VALUES
  ('search', 'en', 'porn', 6, 'explicit'),
  ('search', 'en', 'porno', 6, 'explicit'),
  ('search', 'en', 'pornography', 6, 'explicit'),
  ('search', 'en', 'xxx', 6, 'explicit'),
  ('search', 'en', 'nude', 6, 'explicit'),
  ('search', 'en', 'nudes', 6, 'explicit'),
  ('search', 'en', 'naked', 6, 'explicit'),
  ('search', 'en', 'nsfw', 6, 'explicit'),
  ('search', 'en', 'hentai', 6, 'explicit'),
  ('search', 'en', 'playboy', 6, 'explicit'),
  ('search', 'en', 'onlyfans', 6, 'explicit'),
  ('search', 'en', 'camgirl', 6, 'explicit'),
  ('search', 'en', 'escort', 6, 'explicit'),
  ('search', 'en', 'hookup', 6, 'explicit'),
  ('search', 'en', 'sexy', 6, 'explicit'),
  ('search', 'en', 'sex video', 6, 'explicit'),
  ('search', 'en', 'sex tape', 6, 'explicit'),
  ('search', 'en', 'adult video', 6, 'explicit'),
  ('search', 'en', 'bikini', 5, 'immodest'),
  ('search', 'en', 'lingerie', 5, 'immodest'),
  ('search', 'en', 'cleavage', 5, 'immodest'),
  ('search', 'en', 'miniskirt', 5, 'immodest'),
  ('search', 'en', 'swimwear', 5, 'immodest'),
  ('search', 'en', 'model photoshoot', 5, 'immodest'),
  ('search', 'en', 'immodest', 5, 'immodest'),
  ('search', 'en', 'torah', 2, 'clean'),
  ('search', 'en', 'halacha', 2, 'clean'),
  ('search', 'en', 'gemara', 2, 'clean'),
  ('search', 'en', 'mishnah', 2, 'clean'),
  ('search', 'en', 'chumash', 2, 'clean'),
  ('search', 'en', 'daf yomi', 2, 'clean'),
  ('search', 'en', 'parsha', 2, 'clean'),
  ('search', 'en', 'zmanim', 2, 'clean'),
  ('search', 'en', 'davening', 2, 'clean'),
  ('search', 'en', 'kashrus', 2, 'clean'),
  ('search', 'en', 'siddur', 2, 'clean'),
  ('search', 'en', 'tehillim', 2, 'clean'),
  ('search', 'en', 'shabbos', 2, 'clean'),
  ('search', 'en', 'yeshiva', 2, 'clean'),
  ('search', 'en', 'weather', 2, 'clean'),
  ('search', 'en', 'recipe', 2, 'clean'),
  ('search', 'en', 'directions', 2, 'clean'),
  ('search', 'en', 'dictionary', 2, 'clean'),
  ('search', 'he', 'תורה', 2, 'clean'),
  ('search', 'he', 'הלכה', 2, 'clean'),
  ('search', 'he', 'גמרא', 2, 'clean'),
  ('search', 'he', 'משנה', 2, 'clean'),
  ('search', 'he', 'פרשה', 2, 'clean'),
  ('search', 'he', 'זמנים', 2, 'clean');
