-- Per-rung app matrix (intent only; enforced by Headwind after re-enrolment). GENERATED by
-- scripts/build-app-rules-seed.mjs. 35 rows across the five app policies. Package names are
-- best-known; reconcile against Headwind's installed-apps list on the phone. 24Six's package is a
-- PLACEHOLDER to confirm. X app is blocked on every rung (x.com allowed at rung 5 by the web filter);
-- AI apps allowed only at rung 5 (web-only on 2-4). Re-runnable (clears the seeded policies first).

DELETE FROM app_rules WHERE policy_id IN ('apps_rung_1','apps_rung_2','apps_rung_3','apps_rung_4','apps_rung_5');

INSERT INTO app_rules (policy_id, package_name, state)
VALUES
  ('apps_rung_1', 'com.whatsapp', 'blocked'),
  ('apps_rung_2', 'com.whatsapp', 'allowed'),
  ('apps_rung_3', 'com.whatsapp', 'allowed'),
  ('apps_rung_4', 'com.whatsapp', 'allowed'),
  ('apps_rung_5', 'com.whatsapp', 'allowed'),
  ('apps_rung_1', 'com.twentyfoursix.app', 'allowed'),
  ('apps_rung_2', 'com.twentyfoursix.app', 'allowed'),
  ('apps_rung_3', 'com.twentyfoursix.app', 'allowed'),
  ('apps_rung_4', 'com.twentyfoursix.app', 'allowed'),
  ('apps_rung_5', 'com.twentyfoursix.app', 'allowed'),
  ('apps_rung_1', 'com.spotify.music', 'blocked'),
  ('apps_rung_2', 'com.spotify.music', 'blocked'),
  ('apps_rung_3', 'com.spotify.music', 'blocked'),
  ('apps_rung_4', 'com.spotify.music', 'allowed'),
  ('apps_rung_5', 'com.spotify.music', 'allowed'),
  ('apps_rung_1', 'com.twitter.android', 'blocked'),
  ('apps_rung_2', 'com.twitter.android', 'blocked'),
  ('apps_rung_3', 'com.twitter.android', 'blocked'),
  ('apps_rung_4', 'com.twitter.android', 'blocked'),
  ('apps_rung_5', 'com.twitter.android', 'blocked'),
  ('apps_rung_1', 'com.openai.chatgpt', 'blocked'),
  ('apps_rung_2', 'com.openai.chatgpt', 'blocked'),
  ('apps_rung_3', 'com.openai.chatgpt', 'blocked'),
  ('apps_rung_4', 'com.openai.chatgpt', 'blocked'),
  ('apps_rung_5', 'com.openai.chatgpt', 'allowed'),
  ('apps_rung_1', 'com.anthropic.claude', 'blocked'),
  ('apps_rung_2', 'com.anthropic.claude', 'blocked'),
  ('apps_rung_3', 'com.anthropic.claude', 'blocked'),
  ('apps_rung_4', 'com.anthropic.claude', 'blocked'),
  ('apps_rung_5', 'com.anthropic.claude', 'allowed'),
  ('apps_rung_1', 'com.google.android.apps.bard', 'blocked'),
  ('apps_rung_2', 'com.google.android.apps.bard', 'blocked'),
  ('apps_rung_3', 'com.google.android.apps.bard', 'blocked'),
  ('apps_rung_4', 'com.google.android.apps.bard', 'blocked'),
  ('apps_rung_5', 'com.google.android.apps.bard', 'allowed');
