-- Per-rung app matrix update (intent only; enforced by Headwind after re-enrolment). GENERATED
-- by scripts/build-app-rules-seed.mjs. 140 rows across the five app policies.
--
-- Rung 3 stays on the allowlist model (unchanged). Rung 4 blocks explicit-content AND social-media
-- apps. Rung 5 blocks explicit-content apps only (social allowed there) — this REVERSES the prior
-- "X blocked on every rung" row: X now follows the same social rule as the rest of that bucket.
-- Several package names are best-guess PLACEHOLDERS (see labels in the generator) and must be
-- reconciled against Headwind's installed-apps list once the device is re-enrolled.
--
-- Re-runnable: clears every row for the packages this seed manages, then reinserts. Does not touch
-- any package this seed does not know about.

DELETE FROM app_rules WHERE package_name IN ('com.whatsapp','com.twentyfoursix.app','com.spotify.music','com.openai.chatgpt','com.anthropic.claude','com.google.android.apps.bard','com.twitter.android','com.instagram.android','com.zhiliaoapp.musically','com.snapchat.android','com.facebook.katana','com.facebook.orca','com.reddit.frontpage','com.pinterest','com.tumblr','com.discord','com.tinder','com.bumble.app','co.hinge.app','com.okcupid.okcupid','com.grindrapp.android','com.tranzmate','com.waze','com.gettaxi.android','com.wolt.android','com.mysimpleweb.paybox','com.bank.bit','com.onesecondeveryday.app');

INSERT INTO app_rules (policy_id, package_name, state)
VALUES
  ('apps_rung_1', 'com.whatsapp', 'blocked'),
  ('apps_rung_2', 'com.whatsapp', 'allowed'),
  ('apps_rung_3', 'com.whatsapp', 'allowed'),
  ('apps_rung_4', 'com.whatsapp', 'allowed'),
  ('apps_rung_5', 'com.whatsapp', 'allowed'),
  ('apps_rung_1', 'com.twentyfoursix.app', 'allowed'),
  ('apps_rung_2', 'com.twentyfoursix.app', 'allowed'),
  ('apps_rung_3', 'com.twentyfoursix.app', 'allowed'),
  ('apps_rung_4', 'com.twentyfoursix.app', 'allowed'),
  ('apps_rung_5', 'com.twentyfoursix.app', 'allowed'),
  ('apps_rung_1', 'com.spotify.music', 'blocked'),
  ('apps_rung_2', 'com.spotify.music', 'blocked'),
  ('apps_rung_3', 'com.spotify.music', 'blocked'),
  ('apps_rung_4', 'com.spotify.music', 'allowed'),
  ('apps_rung_5', 'com.spotify.music', 'allowed'),
  ('apps_rung_1', 'com.openai.chatgpt', 'blocked'),
  ('apps_rung_2', 'com.openai.chatgpt', 'blocked'),
  ('apps_rung_3', 'com.openai.chatgpt', 'blocked'),
  ('apps_rung_4', 'com.openai.chatgpt', 'blocked'),
  ('apps_rung_5', 'com.openai.chatgpt', 'allowed'),
  ('apps_rung_1', 'com.anthropic.claude', 'blocked'),
  ('apps_rung_2', 'com.anthropic.claude', 'blocked'),
  ('apps_rung_3', 'com.anthropic.claude', 'blocked'),
  ('apps_rung_4', 'com.anthropic.claude', 'blocked'),
  ('apps_rung_5', 'com.anthropic.claude', 'allowed'),
  ('apps_rung_1', 'com.google.android.apps.bard', 'blocked'),
  ('apps_rung_2', 'com.google.android.apps.bard', 'blocked'),
  ('apps_rung_3', 'com.google.android.apps.bard', 'blocked'),
  ('apps_rung_4', 'com.google.android.apps.bard', 'blocked'),
  ('apps_rung_5', 'com.google.android.apps.bard', 'allowed'),
  ('apps_rung_1', 'com.twitter.android', 'blocked'),
  ('apps_rung_2', 'com.twitter.android', 'blocked'),
  ('apps_rung_3', 'com.twitter.android', 'blocked'),
  ('apps_rung_4', 'com.twitter.android', 'blocked'),
  ('apps_rung_5', 'com.twitter.android', 'allowed'),
  ('apps_rung_1', 'com.instagram.android', 'blocked'),
  ('apps_rung_2', 'com.instagram.android', 'blocked'),
  ('apps_rung_3', 'com.instagram.android', 'blocked'),
  ('apps_rung_4', 'com.instagram.android', 'blocked'),
  ('apps_rung_5', 'com.instagram.android', 'allowed'),
  ('apps_rung_1', 'com.zhiliaoapp.musically', 'blocked'),
  ('apps_rung_2', 'com.zhiliaoapp.musically', 'blocked'),
  ('apps_rung_3', 'com.zhiliaoapp.musically', 'blocked'),
  ('apps_rung_4', 'com.zhiliaoapp.musically', 'blocked'),
  ('apps_rung_5', 'com.zhiliaoapp.musically', 'allowed'),
  ('apps_rung_1', 'com.snapchat.android', 'blocked'),
  ('apps_rung_2', 'com.snapchat.android', 'blocked'),
  ('apps_rung_3', 'com.snapchat.android', 'blocked'),
  ('apps_rung_4', 'com.snapchat.android', 'blocked'),
  ('apps_rung_5', 'com.snapchat.android', 'allowed'),
  ('apps_rung_1', 'com.facebook.katana', 'blocked'),
  ('apps_rung_2', 'com.facebook.katana', 'blocked'),
  ('apps_rung_3', 'com.facebook.katana', 'blocked'),
  ('apps_rung_4', 'com.facebook.katana', 'blocked'),
  ('apps_rung_5', 'com.facebook.katana', 'allowed'),
  ('apps_rung_1', 'com.facebook.orca', 'blocked'),
  ('apps_rung_2', 'com.facebook.orca', 'blocked'),
  ('apps_rung_3', 'com.facebook.orca', 'blocked'),
  ('apps_rung_4', 'com.facebook.orca', 'blocked'),
  ('apps_rung_5', 'com.facebook.orca', 'allowed'),
  ('apps_rung_1', 'com.reddit.frontpage', 'blocked'),
  ('apps_rung_2', 'com.reddit.frontpage', 'blocked'),
  ('apps_rung_3', 'com.reddit.frontpage', 'blocked'),
  ('apps_rung_4', 'com.reddit.frontpage', 'blocked'),
  ('apps_rung_5', 'com.reddit.frontpage', 'allowed'),
  ('apps_rung_1', 'com.pinterest', 'blocked'),
  ('apps_rung_2', 'com.pinterest', 'blocked'),
  ('apps_rung_3', 'com.pinterest', 'blocked'),
  ('apps_rung_4', 'com.pinterest', 'blocked'),
  ('apps_rung_5', 'com.pinterest', 'allowed'),
  ('apps_rung_1', 'com.tumblr', 'blocked'),
  ('apps_rung_2', 'com.tumblr', 'blocked'),
  ('apps_rung_3', 'com.tumblr', 'blocked'),
  ('apps_rung_4', 'com.tumblr', 'blocked'),
  ('apps_rung_5', 'com.tumblr', 'allowed'),
  ('apps_rung_1', 'com.discord', 'blocked'),
  ('apps_rung_2', 'com.discord', 'blocked'),
  ('apps_rung_3', 'com.discord', 'blocked'),
  ('apps_rung_4', 'com.discord', 'blocked'),
  ('apps_rung_5', 'com.discord', 'allowed'),
  ('apps_rung_1', 'com.tinder', 'blocked'),
  ('apps_rung_2', 'com.tinder', 'blocked'),
  ('apps_rung_3', 'com.tinder', 'blocked'),
  ('apps_rung_4', 'com.tinder', 'blocked'),
  ('apps_rung_5', 'com.tinder', 'blocked'),
  ('apps_rung_1', 'com.bumble.app', 'blocked'),
  ('apps_rung_2', 'com.bumble.app', 'blocked'),
  ('apps_rung_3', 'com.bumble.app', 'blocked'),
  ('apps_rung_4', 'com.bumble.app', 'blocked'),
  ('apps_rung_5', 'com.bumble.app', 'blocked'),
  ('apps_rung_1', 'co.hinge.app', 'blocked'),
  ('apps_rung_2', 'co.hinge.app', 'blocked'),
  ('apps_rung_3', 'co.hinge.app', 'blocked'),
  ('apps_rung_4', 'co.hinge.app', 'blocked'),
  ('apps_rung_5', 'co.hinge.app', 'blocked'),
  ('apps_rung_1', 'com.okcupid.okcupid', 'blocked'),
  ('apps_rung_2', 'com.okcupid.okcupid', 'blocked'),
  ('apps_rung_3', 'com.okcupid.okcupid', 'blocked'),
  ('apps_rung_4', 'com.okcupid.okcupid', 'blocked'),
  ('apps_rung_5', 'com.okcupid.okcupid', 'blocked'),
  ('apps_rung_1', 'com.grindrapp.android', 'blocked'),
  ('apps_rung_2', 'com.grindrapp.android', 'blocked'),
  ('apps_rung_3', 'com.grindrapp.android', 'blocked'),
  ('apps_rung_4', 'com.grindrapp.android', 'blocked'),
  ('apps_rung_5', 'com.grindrapp.android', 'blocked'),
  ('apps_rung_1', 'com.tranzmate', 'allowed'),
  ('apps_rung_2', 'com.tranzmate', 'allowed'),
  ('apps_rung_3', 'com.tranzmate', 'allowed'),
  ('apps_rung_4', 'com.tranzmate', 'allowed'),
  ('apps_rung_5', 'com.tranzmate', 'allowed'),
  ('apps_rung_1', 'com.waze', 'allowed'),
  ('apps_rung_2', 'com.waze', 'allowed'),
  ('apps_rung_3', 'com.waze', 'allowed'),
  ('apps_rung_4', 'com.waze', 'allowed'),
  ('apps_rung_5', 'com.waze', 'allowed'),
  ('apps_rung_1', 'com.gettaxi.android', 'allowed'),
  ('apps_rung_2', 'com.gettaxi.android', 'allowed'),
  ('apps_rung_3', 'com.gettaxi.android', 'allowed'),
  ('apps_rung_4', 'com.gettaxi.android', 'allowed'),
  ('apps_rung_5', 'com.gettaxi.android', 'allowed'),
  ('apps_rung_1', 'com.wolt.android', 'allowed'),
  ('apps_rung_2', 'com.wolt.android', 'allowed'),
  ('apps_rung_3', 'com.wolt.android', 'allowed'),
  ('apps_rung_4', 'com.wolt.android', 'allowed'),
  ('apps_rung_5', 'com.wolt.android', 'allowed'),
  ('apps_rung_1', 'com.mysimpleweb.paybox', 'allowed'),
  ('apps_rung_2', 'com.mysimpleweb.paybox', 'allowed'),
  ('apps_rung_3', 'com.mysimpleweb.paybox', 'allowed'),
  ('apps_rung_4', 'com.mysimpleweb.paybox', 'allowed'),
  ('apps_rung_5', 'com.mysimpleweb.paybox', 'allowed'),
  ('apps_rung_1', 'com.bank.bit', 'allowed'),
  ('apps_rung_2', 'com.bank.bit', 'allowed'),
  ('apps_rung_3', 'com.bank.bit', 'allowed'),
  ('apps_rung_4', 'com.bank.bit', 'allowed'),
  ('apps_rung_5', 'com.bank.bit', 'allowed'),
  ('apps_rung_1', 'com.onesecondeveryday.app', 'allowed'),
  ('apps_rung_2', 'com.onesecondeveryday.app', 'allowed'),
  ('apps_rung_3', 'com.onesecondeveryday.app', 'allowed'),
  ('apps_rung_4', 'com.onesecondeveryday.app', 'allowed'),
  ('apps_rung_5', 'com.onesecondeveryday.app', 'allowed');
