-- Temporary VPN access on Yeshiva rung 3, with or without YouTube.
-- Explicit allowed rules are required: deleting a blocked rule leaves the existing
-- Headwind Remove link intact when pushPolicyApps merges the configuration.
-- Apply this migration, then Push apps for BOTH rung-3 policies in /admin.
-- Android always-on VPN lockdown is separate; see YESHIVA.md.
-- To revoke: set these same rules to blocked in a new migration and push both policies.
INSERT INTO app_rules (policy_id, package_name, state) VALUES
  ('yeshiva_rung_3', 'com.nordvpn.android', 'allowed'),
  ('yeshiva_rung_3', 'com.expressvpn.vpn', 'allowed'),
  ('yeshiva_rung_3', 'com.surfshark.vpnclient.android', 'allowed'),
  ('yeshiva_rung_3', 'ch.protonvpn.android', 'allowed'),
  ('yeshiva_rung_3', 'hotspotshield.android.vpn', 'allowed'),
  ('yeshiva_rung_3', 'com.psiphon3', 'allowed'),
  ('yeshiva_rung_3', 'org.torproject.android', 'allowed'),
  ('yeshiva_rung_3', 'free.vpn.unblock.proxy.turbovpn', 'allowed'),
  ('yeshiva_rung_3', 'com.cloudflare.onedotonedotonedotone', 'allowed'),
  ('yeshiva_rung_3', 'com.tunnelbear.android', 'allowed'),
  ('yeshiva_rung_3', 'com.privateinternetaccess.android', 'allowed'),
  ('yeshiva_rung_3', 'com.windscribe.vpn', 'allowed'),
  ('yeshiva_rung_3', 'net.openvpn.openvpn', 'allowed'),
  ('yeshiva_rung_3', 'de.blinkt.openvpn', 'allowed'),
  ('yeshiva_rung_3', 'com.v2ray.ang', 'allowed'),
  ('yeshiva_rung_3', 'com.github.shadowsocks', 'allowed'),
  ('yeshiva_rung_3', 'org.outline.android.client', 'allowed'),
  ('yeshiva_rung_3', 'com.kaspersky.secure.connection', 'allowed'),
  ('yeshiva_rung_3', 'com.avast.android.vpn', 'allowed'),
  ('yeshiva_rung_3', 'com.zenmate.android', 'allowed'),
  ('yeshiva_rung_3', 'com.cyberghost.android', 'allowed'),
  ('yeshiva_rung_3', 'com.ivpn.client', 'allowed'),
  ('yeshiva_rung_3', 'com.mullvad.mullvadvpn', 'allowed'),
  ('yeshiva_rung_3_yt', 'com.nordvpn.android', 'allowed'),
  ('yeshiva_rung_3_yt', 'com.expressvpn.vpn', 'allowed'),
  ('yeshiva_rung_3_yt', 'com.surfshark.vpnclient.android', 'allowed'),
  ('yeshiva_rung_3_yt', 'ch.protonvpn.android', 'allowed'),
  ('yeshiva_rung_3_yt', 'hotspotshield.android.vpn', 'allowed'),
  ('yeshiva_rung_3_yt', 'com.psiphon3', 'allowed'),
  ('yeshiva_rung_3_yt', 'org.torproject.android', 'allowed'),
  ('yeshiva_rung_3_yt', 'free.vpn.unblock.proxy.turbovpn', 'allowed'),
  ('yeshiva_rung_3_yt', 'com.cloudflare.onedotonedotonedotone', 'allowed'),
  ('yeshiva_rung_3_yt', 'com.tunnelbear.android', 'allowed'),
  ('yeshiva_rung_3_yt', 'com.privateinternetaccess.android', 'allowed'),
  ('yeshiva_rung_3_yt', 'com.windscribe.vpn', 'allowed'),
  ('yeshiva_rung_3_yt', 'net.openvpn.openvpn', 'allowed'),
  ('yeshiva_rung_3_yt', 'de.blinkt.openvpn', 'allowed'),
  ('yeshiva_rung_3_yt', 'com.v2ray.ang', 'allowed'),
  ('yeshiva_rung_3_yt', 'com.github.shadowsocks', 'allowed'),
  ('yeshiva_rung_3_yt', 'org.outline.android.client', 'allowed'),
  ('yeshiva_rung_3_yt', 'com.kaspersky.secure.connection', 'allowed'),
  ('yeshiva_rung_3_yt', 'com.avast.android.vpn', 'allowed'),
  ('yeshiva_rung_3_yt', 'com.zenmate.android', 'allowed'),
  ('yeshiva_rung_3_yt', 'com.cyberghost.android', 'allowed'),
  ('yeshiva_rung_3_yt', 'com.ivpn.client', 'allowed'),
  ('yeshiva_rung_3_yt', 'com.mullvad.mullvadvpn', 'allowed')
ON CONFLICT(policy_id, package_name) DO UPDATE SET state = excluded.state;
